blog/urls.py
from django.urls import path
from .views import (
    ArticleListView,
    ArticleDetailView
)

app_name = 'blog'
urlpatterns = [
    path('', ArticleListView.as_view(), name='blog-list'),
    path('<int:pk>/<title>', ArticleDetailView.as_view(), name='blog-detail'),
]

core/urls.py
from django.urls import path

from metallurgy.views import (
    WorkSampleListView,
    WorkSampleDetailView,
    WorkSampleCategoryListView,
    CategoriesListView
)
from .views import (
    Home,
    AboutUsView,
    CreateContactView,
    PlatformMvpView,
    IronCalculatorTemplateView
)

app_name = 'core'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('about-us/', AboutUsView.as_view(), name='about-us'),
    path('contact-us/', CreateContactView.as_view(), name='contact-us'),
    # path('faq/', QuestionListView.as_view(), name='faq'),
    path('calculator/', IronCalculatorTemplateView.as_view(), name='calculator'),
    path('vehicles/', PlatformMvpView.as_view(), name='platform-mvp'),

    path('portfolios/', WorkSampleListView.as_view(), name='work-sample-list'),
    path('portfolios/categories/', CategoriesListView.as_view(), name='work-sample-categories'),
    path(r'portfolios/category-<slug>/<int:pk>', WorkSampleCategoryListView.as_view(),
         name='work-sample-category-list'),
    path('portfolios/<int:pk>/<str:title>', WorkSampleDetailView.as_view(), name='work-sample-detail'),
]

metallurgy/urls.py
from django.urls import path
from .views import (
    metallurgy_landing_view,
    CustomerProjectsListView,
    CustomerProjectDetailView,
    CustomerInvoiceDetailView,
)

app_name = 'metallurgy'
urlpatterns = [
    path('', metallurgy_landing_view, name='landing'),

    path('customer/projects/', CustomerProjectsListView.as_view(), name='customer-project-list'),
    path('customer/projects/<int:pk>', CustomerProjectDetailView.as_view(), name='customer-project-detail'),

    path('customer/invoices/<int:pk>', CustomerInvoiceDetailView.as_view(), name='customer-invoice-detail'),
]

picofelez/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from blog.sitemap import ArticleSitemap
from core.sitemap import StaticViewSitemap
from metallurgy.sitemap import WorkSampleSitemap
from product.sitemap import ProductSitemap, CategorySitemap

sitemaps = {
    "statics": StaticViewSitemap,
    "products": ProductSitemap,
    "portfolio": WorkSampleSitemap,
    "articles": ArticleSitemap,
    "categories": CategorySitemap
}

urlpatterns = [
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap"
    ),

    path('', include('core.urls')),
    path('products/', include('product.urls')),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls')),
    path('metallurgy/', include('metallurgy.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models

from cart.models import User


# Create your models here.


class Question(models.Model):
    """
    The Question main model.
    """

    class StatusChoices(models.TextChoices):
        active = 'a', 'فعال'
        deactivate = 'da', 'غیرفعال'

    title = models.CharField(max_length=120, verbose_name='عنوان')
    description = models.TextField(verbose_name='توضیحات')
    status = models.CharField(
        max_length=5, choices=StatusChoices.choices, default=StatusChoices.active, verbose_name='وضعیت نمایش'
    )
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')

    class Meta:
        verbose_name = 'سوال'
        verbose_name_plural = 'سوالات متداول'

    def __str__(self):
        return self.title


class Rating(models.Model):
    """
    The Rating main model,
    GenericRelation.
    """
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='ratings', null=True, blank=True, verbose_name='کاربر'
    )
    stars = models.IntegerField(null=True, blank=True, verbose_name='ستاره ها')
    comment = models.TextField(null=True, blank=True, verbose_name='کامنت')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.CharField(max_length=255)
    content_object = GenericForeignKey('content_type', 'object_id')
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True, verbose_name='تاریخ ایجاد')

    class Meta:
        indexes = [
            models.Index(fields=["content_type", "object_id"]),
        ]
        verbose_name = 'امتیاز'
        verbose_name_plural = 'امتیاز ها'

    def __str__(self):
        return f"{self.content_type}"

core/forms.py
from django import forms


class RatingForm(forms.Form):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )

    comment = forms.CharField(
        widget=forms.Textarea,
        required=False
    )
    rating = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices=RATING_CHOICES,
        required=False
    )

core/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView
from django.utils import timezone

from core.models import Question
from metallurgy.models import WorkSample
from shop.forms import ContactForm


# Create your views here.


class Home(TemplateView):
    """
    index view.
    """

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['portfolio'] = WorkSample.objects.filter(status='p', publish_time__lte=timezone.now())[:3]
        return data

    template_name = 'core/home.html'


class AboutUsView(TemplateView):
    """
    About us view.
    """
    template_name = 'core/about-us.html'


class CreateContactView(SuccessMessageMixin, CreateView):
    """
    Contact us view.
    """
    template_name = 'core/contact_us.html'
    form_class = ContactForm
    success_url = reverse_lazy('core:contact-us')
    success_message = 'پیام شما با موفقیت ارسال شد. با شما تماس خواهیم گرفت!'


class QuestionListView(ListView):
    """
    Faq view.
    """
    queryset = Question.objects.filter(status='a')
    template_name = 'core/faq.html'


class IronCalculatorTemplateView(TemplateView):
    template_name = 'core/calculator.html'


class PlatformMvpView(TemplateView):
    template_name = 'core/plat_mvp.html'

core/templates/core/home.html
{% extends 'core/base/_base.html' %}
{% load static %}
{% block title %}پیکوفلز | گروه فلزکاری عبدی{% endblock %}

{% block content %}
    <section class="intro-box">
        <section class="container position-relative py-5">
            <div class="row justify-content-center mb-4 mt-4">
                <div class="col-xl-7 col-lg-9 text-center">
                    <h1 class="font-vazir-bold-fd mb-3">
                        <span class="text-purple">پیکو</span>فلز
                    </h1>
                    <p class="mb-0 font-vazir-bold-f">
                        ارائه دهنده انواع خدمات و محصولات فلزی منحصر به فرد!
                    </p>
                </div>
            </div>
            <div class="text-center mb-5">
                <a href="{% url 'core:work-sample-categories' %}" class="btn btn-outline-dark px-4 py-2">
                    <i class="fas fa-newspaper"></i>
                    خدمات ما
                </a>
                <a href="{% url 'core:contact-us' %}" class="btn btn-outline-dark px-4 py-2">
                    <i class="fas fa-phone"></i>
                    همکاری با ما
                </a>
            </div>
            <div class="row icon-boxes mb-5">
                <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
                    <div class="icon-box">
                        <div class="icon"><i class="fas fa-shop"></i></div>
                        <h4 class="icon-box-title">
                            <a href="{% url 'core:work-sample-list' %}">انتخاب محصول</a>
                        </h4>
                        <p class="description">
                            از پروژه های ما بازدید کنید ، محصول خودرا انتخاب و با ما
                            تماس بگیرید!
                        </p>
                    </div>
                </div>

                <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
                    <div class="icon-box">
                        <div class="icon"><i class="fas fa-gear"></i></div>
                        <h4 class="icon-box-title">
                            <a href="{% url 'core:contact-us' %}">
                                بازدید فنی
                            </a>
                        </h4>
                        <p class="description">
                            پس از انتخاب محصول با حضور در محل پروژه بازدید فنی و الگو برداری دقیق صورت میگیرد!
                        </p>
                    </div>
                </div>

                <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
                    <div class="icon-box">
                        <div class="icon"><i class="fas fa-screwdriver-wrench"></i></div>
                        <h4 class="icon-box-title">
                            <a href="{% url 'core:about-us' %}">
                                ساخت و تولید
                            </a>
                        </h4>
                        <p class="description">سفارش شما با تجهیزات به روز و حرفه ای و با رعایت اصول مهندسی، طراحی و
                            تولید می شود!
                        </p>
                    </div>
                </div>

                <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
                    <div class="icon-box">
                        <div class="icon"><i class="fas fa-truck"></i></div>
                        <h4 class="icon-box-title">
                            <a href="{% url 'blog:blog-list' %}">
                                نصب و اجرا
                            </a>
                        </h4>
                        <p class="description">
                            پس از اتمام ساخت، بارگیری به محل پروژه انجام و درصورت نیاز توسط تیم متخصص
                            نصب میشود!
                        </p>
                    </div>
                </div>

            </div>
        </section>
    </section>

    <section id="call-info" class="call-info my-4">
        <section class="container">
            <div class="row align-items-center">
                <div class="col-12 col-md-7 mb-3">
                    {#                    <h3 class="h6 text-center">صنایع فلزی - ساختمانی</h3>#}
                    {#                    <h2 class="h4 my-4 text-center">گروه فلزکاری عبدی (پیکوفلز)</h2>#}
                    <h2 class="h5 my-4 text-center font-vazir-bold-fd">شصت سال سابقه در صنعت فلزکاری!</h2>
                    <p class="call-info-text text-center">
                        <b>گروه فلزکاری عبدی</b> مفتخر به 60 سال سابقه در ارائه انواع محصولات و خدمات فلزی و آهنگری
                        همچون
                        طراحی، تولید و اجرای انواع اسکلت فلزی، فلاشینگ، لانچر، شاسی دستگاه های صنعتی، شاسی کشی نما،
                        فرفورژه، انواع درب و پنجره آهنی، تانکر، تیرچه کرومیت، اسکلت تیرچه های پاشنه بتنی، وال پست و ...
                        می باشد.
                    </p>
                    <p class="call-info-text text-center">
                        کارگاه مرکزی گروه صنعتی <b>پیکوفلز</b> در استان البرز مستقر شده است و به سراسر ایران همچون
                        تهران،
                        زنجان، گیلان، مازندران و ... خدمات و محصولات فلزی خود را ارائه می دهد. با گسترش تکنولوژی و رشد
                        ابزارآلات صنعتی، مجموعه ما همواره تلاش کرده است تا با بهره گیری از علم و دانش مهندسی روز، توسعه
                        منابع انسانی و قرار گیری در مسیر رشد و توسعه کسب و کار، بهترین خدمات و محصولات را برای مشتریان
                        فراهم کند.
                    </p>
                </div>
                <div class="col-12 col-md-5">
                    <img src="{% static 'site_statics/img/bg/14.jpg' %}" alt="شهر" class="rounded-3" width="100%"
                         height="300">
                </div>
            </div>
        </section>
    </section>
    <hr>
    <section id="services" class="services">
        <section class="container">
            <h3 class="font-vazir-bold-fd h4 text-center mb-4">
                سرویس های ما
            </h3>
            <section class="row">
                {% for category in pinned_categories %}
                    <section class="col-md-4 col-12 mb-3">
                        <div class="services-card">
                            <img src="{{ category.image_url }}" alt="services">
                            <div class="services-card-overlay">
                                <div class="mb-4">
                                    <i class="{{ category.icon }}"></i>
                                </div>
                                <p class="title h5 mb-4 font-vazir-bold-fd">
                                    <a href="{% url 'core:work-sample-category-list' category.slug category.pk %}">
                                        {{ category.name }}
                                    </a>
                                </p>
                                <p class="services-text mb-4">
                                    {{ category.summary|safe }}
                                </p>
                            </div>
                        </div>
                    </section>
                {% endfor %}

            </section>
        </section>
    </section>
    <hr>
    <section class="home-product my-5">
        <section class="container">
            <!-- title -->
            <div class="row">
                <div class="col-12 mb-2">
                    <h4 class="font-vazir-bold-fd text-center mb-4">پروژه ها</h4>
                </div>
            </div>
            <!-- products -->
            <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-4 g-md-4 products justify-content-center">
                {% for worksample in latest_portfolios %}
                    <section class="col-lg-4 col-md-6 col-12 mb-3">
                        {% include 'metallurgy/components/portfolio_card_component.html' %}
                    </section>
                {% endfor %}

            </div>
            <div class="d-flex justify-content-center">
                <a href="{% url 'core:work-sample-list' %}" class="btn btn-purple mt-2">
                    مشاهده همه پروژه ها</a>
            </div>
        </section>
    </section>
    <hr>

    <section id="contact-info" class="contact-info">
        <section class="container">
            <section class="text-center">
                <h4 class="font-vazir-bold-fd">همکاری با ما</h4>
            </section>
            <section class="row mt-4 mx-2 mx-md-0">
                <section class="col-md-3 col-12 mb-3">
                    <a href="{% url 'core:contact-us' %}" class="contact-info-card rounded flex-center">
                            <span>
                                <i class="fas fa-building"></i>
                            </span>
                        <p>
                            جوشکاری نمای ساختمان<br>
                            <small>مشاوره و همکاری</small>
                        </p>
                    </a>
                </section>
                <section class="col-md-3 col-12 mb-3">
                    <a href="{% url 'core:contact-us' %}" class="contact-info-card rounded flex-center">
                            <span>
                                <i class="fas fa-door-closed"></i>
                            </span>
                        <p>
                            درب، پنجره، حفاظ<br>
                            <small>مشاوره و همکاری</small>
                        </p>
                    </a>
                </section>
                <section class="col-md-3 col-12 mb-3">
                    <a href="{% url 'core:contact-us' %}" class="contact-info-card rounded flex-center">
                            <span>
                                <i class="fas fa-industry"></i>
                            </span>
                        <p>
                            فرفورژه و دکوراسیون<br>
                            <small>مشاوره و همکاری</small>
                        </p>
                    </a>
                </section>
                <section class="col-md-3 col-12 mb-3">
                    <a href="{% url 'core:contact-us' %}" class="contact-info-card rounded flex-center">
                            <span>
                                <i class="fas fa-tools"></i>
                            </span>
                        <p>
                            محصولات فلزی دیگر<br>
                            <small>مشاوره و همکاری</small>
                        </p>
                    </a>
                </section>
            </section>
        </section>
    </section>
    <hr>
    <section id="products" class="products">

        <div class="container">
            <div class="row">
                <h3 class="font-vazir-bold-fd h4 text-center mb-4">
                    محصولات
                </h3>
                {% for product in latest_multiple_products %}
                    {% include 'product/components/multiple_product_card_component.html' %}
                {% empty %}
                    <div class="col-12">
                        <div class="alert alert-secondary">محصولی یافت نشد.</div>
                    </div>
                {% endfor %}

            </div>
            {% include 'core/components/paginate_component.html' %}
        </div>
    </section>

    <hr>

    {#    <section class="my-5">#}
    {#        <section class="text-center contact-info-title">#}
    {#            <p class="h5 font-vazir-bold-fd">کارفرما هایی که به ما اعتماد کرده اند</p>#}
    {#        </section>#}
    {#        <div class="container">#}
    {#                <div class="slider">#}
    {#                    <div class="slide-track">#}
    {#                        <div class="slide">#}
    {#                            <img src="https://www.rasha-paper.com/wp-content/uploads/2017/09/rasha-persian-logo.png.webp"#}
    {#                                 alt="راشا کاسپین"/>#}
    {#                        </div>#}
    {#                    </div>#}
    {#                </div>#}
    {#        </div>#}
    {#    </section>#}
    {##}

    <section class="home-article my-5">
        <section class="container">
            <!-- title -->
            <div class="row justify-content-center">
                <div class="col-12">
                    <h5 class="text-center h4 font-vazir-bold-fd mb-4">نوشته های اخیر</h5>
                </div>
            </div>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-4 g-md-4 products justify-content-center">
                {% for article in latest_articles %}
                    {% include 'blog/components/article_card_component.html' %}
                {% endfor %}
            </div>

            <div class="d-flex justify-content-center">
                <a href="{% url 'blog:blog-list' %}" class="btn btn-outline-purple mt-2">
                    مجله پیکوفلز</a>
            </div>
        </section>
    </section>

{% endblock %}

core/templates/core/plat_mvp.html
{% extends 'core/base/_base.html' %}
{% load static %}

{% block analytics_script %}{% endblock %}

{% block meta_tags %}{% endblock %}

{% block title %}پیکوابزار | مرجع آنلاین ابزار{% endblock %}

{% block header_content %}
    {% include 'core/base/_plat_mvp_header.html' %}
{% endblock %}

{% block footer_content %}
{% endblock %}


{% block content %}
    <section class="intro-box">
        <section class="container position-relative py-5">
            <div class="row justify-content-center mb-4 mt-4">
                <div class="col-xl-7 col-lg-9 text-center">
                    <h1 class="font-vazir-bold-fd mb-3">
                        مرجع آنلاین
                        <span class="text-purple">ابزار</span>
                    </h1>
                    <p class="mb-0 font-vazir-bold-f">
                        قیمت های لحظه ای ابزار هارو ببین و در لحظه خرید کن!
                    </p>
                </div>
            </div>
            <div class="text-center mb-5">
                <a href="{% url 'core:work-sample-categories' %}" class="btn btn-outline-dark px-4 py-2">
                    <i class="fas fa-newspaper"></i>
                    لیست قیمت ابزار
                </a>
                <a href="{% url 'core:contact-us' %}" class="btn btn-outline-dark px-4 py-2">
                    <i class="fas fa-phone"></i>
                    لیست محصولات
                </a>
                <br>
                <a href="{% url 'core:contact-us' %}" class="btn btn-outline-dark mt-2 px-4 py-2">
                    <i class="fas fa-store"></i>
                    فروشنده شوید
                </a>
            </div>
            <div class="row icon-boxes mb-5">
                <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
                    <div class="icon-box">
                        <div class="icon"><i class="fas fa-shop"></i></div>
                        <h4 class="icon-box-title">
                            <a href="{% url 'core:work-sample-list' %}">انتخاب محصول</a>
                        </h4>
                        <p class="description">
                            از پروژه های ما بازدید کنید ، محصول خودرا انتخاب و با ما
                            تماس بگیرید!
                        </p>
                    </div>
                </div>

                <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
                    <div class="icon-box">
                        <div class="icon"><i class="fas fa-gear"></i></div>
                        <h4 class="icon-box-title">
                            <a href="{% url 'core:contact-us' %}">
                                بازدید فنی
                            </a>
                        </h4>
                        <p class="description">
                            پس از انتخاب محصول با حضور در محل پروژه بازدید فنی و الگو برداری دقیق صورت میگیرد!
                        </p>
                    </div>
                </div>

                <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
                    <div class="icon-box">
                        <div class="icon"><i class="fas fa-screwdriver-wrench"></i></div>
                        <h4 class="icon-box-title">
                            <a href="{% url 'core:about-us' %}">
                                ساخت و تولید
                            </a>
                        </h4>
                        <p class="description">سفارش شما با تجهیزات به روز و حرفه ای و با رعایت اصول مهندسی، طراحی و
                            تولید می شود!
                        </p>
                    </div>
                </div>

                <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
                    <div class="icon-box">
                        <div class="icon"><i class="fas fa-truck"></i></div>
                        <h4 class="icon-box-title">
                            <a href="{% url 'blog:blog-list' %}">
                                نصب و اجرا
                            </a>
                        </h4>
                        <p class="description">
                            پس از اتمام ساخت، بارگیری به محل پروژه انجام و درصورت نیاز توسط تیم متخصص
                            نصب میشود!
                        </p>
                    </div>
                </div>

            </div>
        </section>
    </section>
    <section id="contact-info" class="contact-info">
        <section class="container">
            {#            <section class="text-center">#}
            {#                <h4 class="font-vazir-bold-fd">همکاری با ما</h4>#}
            {#            </section>#}
            <section class="row mt-4 mx-2 mx-md-0">
                <section class="col-md-3 col-6 mb-3">
                    <a href="{% url 'core:contact-us' %}" class="contact-info-card rounded flex-center">
                            <span>
                                <i class="fas fa-building"></i>
                            </span>
                        <p>
                            ابزار برقی<br>
                            <small>استعلام قیمت</small>
                        </p>
                    </a>
                </section>
                <section class="col-md-3 col-6 mb-3">
                    <a href="{% url 'core:contact-us' %}" class="contact-info-card rounded flex-center">
                            <span>
                                <i class="fas fa-door-closed"></i>
                            </span>
                        <p>
                            ابزار دستی<br>
                            <small>استعلام قیمت</small>
                        </p>
                    </a>
                </section>
                <section class="col-md-3 col-6 mb-3">
                    <a href="{% url 'core:contact-us' %}" class="contact-info-card rounded flex-center">
                            <span>
                                <i class="fas fa-industry"></i>
                            </span>
                        <p>
                            یراق آلات<br>
                            <small>استعلام قیمت</small>
                        </p>
                    </a>
                </section>
                <section class="col-md-3 col-6 mb-3">
                    <a href="{% url 'core:contact-us' %}" class="contact-info-card rounded flex-center">
                            <span>
                                <i class="fas fa-tools"></i>
                            </span>
                        <p>
                            ابزار کارگاهی<br>
                            <small>استعلام قیمت</small>
                        </p>
                    </a>
                </section>
            </section>
        </section>
    </section>
{% endblock %}