blog/urls.py
from django.urls import path
from .views import (
    ArticleListView,
    ArticleDetailView
)

app_name = 'blog'
urlpatterns = [
    path('', ArticleListView.as_view(), name='blog-list'),
    path('<int:pk>/<title>', ArticleDetailView.as_view(), name='blog-detail'),
]

picofelez/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from blog.sitemap import ArticleSitemap
from core.sitemap import StaticViewSitemap
from metallurgy.sitemap import WorkSampleSitemap
from product.sitemap import ProductSitemap, CategorySitemap

sitemaps = {
    "statics": StaticViewSitemap,
    "products": ProductSitemap,
    "portfolio": WorkSampleSitemap,
    "articles": ArticleSitemap,
    "categories": CategorySitemap
}

urlpatterns = [
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap"
    ),

    path('', include('core.urls')),
    path('products/', include('product.urls')),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls')),
    path('metallurgy/', include('metallurgy.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import (
    ShopDetailView,
    create_shop_contact,
    ShopProductsView,
    ShopRatingView,

    ShopListView,
    register_shop,
    register_shop_seller_information_create,
    register_shop_create,

    # panel
    ShopAccountMainView,
    ShopProductsListView,
    ShopProductUpdateView,
    ShopProductCreateView,
    ShopOrderListView,
    ShopOrderDetailView,
    ShopOrderUpdateView,
    ShopUpdateView,
    shop_wallet_view,
    ShopUpdateProductPriceView,
    ShopInvoiceListListView,
    ShopInvoiceDetailDetailView,
    create_shop_invoice_view,
    update_shop_invoice_view,
    customer_for_invoice_ajax_view
)

app_name = 'shop'
urlpatterns = [
    path('shops/register-shop/', register_shop, name='register-shop'),
    path('shops/', ShopListView.as_view(), name='shop-list'),
    path('<slug>', ShopDetailView.as_view(), name='shop-detail'),
    path('<slug>/contact', create_shop_contact, name='shop-contact'),
    path('<slug>/products', ShopProductsView.as_view(), name='shop-products'),
    path('<slug>/rating', ShopRatingView.as_view(), name='shop-rating'),

    # ajax urls
    path(
        'shops/register-shop/seller-information-create',
        register_shop_seller_information_create,
        name='seller-information-create'
    ),
    path(
        'shops/register-shop/data-create',
        register_shop_create,
        name='shop-data-create'
    ),

    # panel
    path('shop/panel/<unique_uuid>', ShopAccountMainView.as_view(), name='shop-panel-main'),
    path('shop/panel/<unique_uuid>/update', ShopUpdateView.as_view(), name='shop-panel-update'),
    # path('shop/panel/<unique_uuid>/wallet', shop_wallet_view, name='shop-panel-wallet'),

    # path(
    #     'shop/panel/<unique_uuid>/products',
    #     ShopProductsListView.as_view(),
    #     name='shop-panel-products'
    # ),
    # path(
    #     'shop/panel/<unique_uuid>/products/update/<str:pk>',
    #     ShopProductUpdateView.as_view(),
    #     name='shop-panel-products-update'
    # ),
    # path(
    #     'shop/panel/<unique_uuid>/products/update/price/<str:pk>',
    #     ShopUpdateProductPriceView.as_view(),
    #     name='shop-panel-products-update-price'
    # ),
    # path(
    #     'shop/panel/<unique_uuid>/products/create',
    #     ShopProductCreateView.as_view(),
    #     name='shop-panel-products-create'
    # ),

    # path(
    #     'shop/panel/<unique_uuid>/orders',
    #     ShopOrderListView.as_view(),
    #     name='shop-panel-orders'
    # ),
    # path(
    #     'shop/panel/<unique_uuid>/orders/<int:pk>',
    #     ShopOrderDetailView.as_view(),
    #     name='shop-panel-orders-detail'
    # ),
    # path(
    #     'shop/panel/<unique_uuid>/orders/update/<int:pk>',
    #     ShopOrderUpdateView.as_view(),
    #     name='shop-panel-orders-update'
    # ),

    # special shops
    path(
        'shop/panel/<unique_uuid>/invoices',
        ShopInvoiceListListView.as_view(),
        name='shop-panel-invoices'
    ),
    path(
        'shop/panel/<unique_uuid>/invoices/create',
        create_shop_invoice_view,
        name='shop-panel-invoices-create'
    ),
    path(
        'shop/panel/<unique_uuid>/invoices/create/customer',
        customer_for_invoice_ajax_view,
        name='shop-panel-invoices-create-customer'
    ),
    path(
        'shop/panel/<unique_uuid>/invoices/update/<str:pk>',
        update_shop_invoice_view,
        name='shop-panel-invoices-update'
    ),
    path(
        'shop/panel/<unique_uuid>/invoices/<str:pk>',
        ShopInvoiceDetailDetailView.as_view(),
        name='shop-panel-invoices-detail'
    ),
]

shop/models.py
import uuid

from django.db import models
from django.urls import reverse
from django.utils.html import format_html

from account.models import User
from extensions.utils import upload_shop_image_path, jalali_converter, generate_product_id
from .managers import ActiveShopManager, ShopInvoiceManager
from django_jalali.db import models as jmodels


# Create your models here.


class Shop(models.Model):
    """
    The Shop main model,
    Many-To-One relationship with User.
    """

    class StatusChoices(models.TextChoices):
        active = 'a', 'فعال'
        deactivate = 'da', 'غیرفعال'
        block = 'b', 'بلاک شده'
        spam = 's', 'اسپم'

    unique_uuid = models.UUIDField(unique=True, null=True, blank=True)
    title = models.CharField(max_length=155, verbose_name='نام نمایشی فروشگاه')
    slug = models.SlugField(null=True, blank=True, unique=True, verbose_name='شناسه اسلاگ')
    image = models.ImageField(upload_to=upload_shop_image_path, null=True, blank=True, verbose_name='تصویر')
    owner = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name='shops', verbose_name='مدیر فروشگاه'
    )
    location = models.CharField(max_length=100, verbose_name='مکان')
    status = models.CharField(
        max_length=4, choices=StatusChoices.choices, default=StatusChoices.active, verbose_name='وضعیت فروشگاه'
    )
    demand = models.TextField(
        null=True, blank=True, verbose_name='تقاضا'
    )
    supply = models.TextField(
        null=True, blank=True, verbose_name='عرضه'
    )
    about = models.TextField(verbose_name='متن دباره ما')
    is_special = models.BooleanField(default=False, null=True, blank=True, verbose_name='برگزیده')
    is_special_date = models.DateTimeField(null=True, blank=True, verbose_name='تاریخ برگزیده شدن')
    score = models.IntegerField(default=0, verbose_name='امتیاز')
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')
    updated = models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')

    class Meta:
        verbose_name = 'فروشگاه'
        verbose_name_plural = '1. فروشگاه ها'
        ordering = ('-score',)

    objects = models.Manager()
    active = ActiveShopManager()

    def increase_score(self, increase_count, summary):
        self.score_histories.create(
            value=increase_count,
            summary=summary
        )
        self.score += increase_count
        self.save()

    def get_thumbnail(self):
        return format_html(f"<img width=100 height=75 style='border-radius: 5px;' src='{self.image.url}'>")

    get_thumbnail.short_description = "تصویر فروشگاه"

    def get_absolute_url(self):
        return reverse('shop:shop-detail', args=[self.slug])

    def __str__(self):
        return self.title


class Contact(models.Model):
    """
    The contact main model,
    Many-To-One relationship with Shop.
    """

    class StatusChoices(models.TextChoices):
        read = 'r', 'خوانده شده'  # read
        unread = 'ur', 'خوانده نشده'  # unread

    full_name = models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')
    subject = models.CharField(max_length=100, null=True, blank=True, verbose_name='موضوع')
    phone = models.CharField(max_length=12, verbose_name='شماره تلفن')  # phone number
    message = models.TextField(verbose_name='پیام')
    shop = models.ForeignKey(
        Shop, on_delete=models.CASCADE, null=True, blank=True, related_name='contacts', verbose_name='فروشگاه گیرنده'
    )
    status = models.CharField(
        max_length=4, choices=StatusChoices.choices, default=StatusChoices.unread, verbose_name='وضعیت مشاهده'
    )
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')
    updated = models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')

    class Meta:
        verbose_name = 'پیام'
        verbose_name_plural = '2. پیام ها'
        ordering = ('-created',)

    def __str__(self):
        return self.full_name


class SellerInformation(models.Model):
    """
    The SellerInformation main model,
    Many-To-One relationship with Shop.
    """

    phone_number = models.CharField(max_length=11, verbose_name='شماره تلفن')
    full_name = models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')
    national_code = models.CharField(max_length=10, verbose_name='کدملی')
    shop = models.ForeignKey(
        Shop, on_delete=models.PROTECT, related_name='sellers', verbose_name='فروشگاه'
    )
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')
    updated = models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')

    class Meta:
        verbose_name_plural = '3. اطلاعات فروشندگان'
        verbose_name = 'اطلاعات فروشنده'

    def __str__(self):
        return f"{self.shop} | {self.full_name}"


class Wallet(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name='wallets', verbose_name='کاربر'
    )
    shop = models.ForeignKey(
        Shop, on_delete=models.PROTECT, related_name='shops', verbose_name='فروشگاه'
    )
    balance = models.BigIntegerField(default=0, verbose_name='موجودی')
    sheba = models.CharField(max_length=255, null=True, blank=True, verbose_name='شماره شبا')
    confirmed = models.BooleanField(default=False, verbose_name='تائید شده/نشده')
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')
    updated = models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')

    class Meta:
        verbose_name_plural = '4. کیف پول ها'
        verbose_name = 'کیف پول'
        ordering = ('-created',)

    def created_jalali(self):
        return f"{jalali_converter(self.created)} ساعت {self.created.hour}:{self.created.minute}"

    created_jalali.short_description = 'تاریخ ایجاد'

    def updated_jalali(self):
        return f"{jalali_converter(self.updated)} ساعت {self.updated.hour}:{self.updated.minute}"

    updated_jalali.short_description = 'تاریخ آخرین ویرایش'

    def get_balance(self):
        return f"{self.balance:,} ت"

    get_balance.short_description = 'موجودی'

    def deposit(self, value):
        self.transactions.create(
            value=value,
            running_balance=self.balance + value,
            transaction_type='d',  # deposit
            transaction_status=True
        )
        self.balance += value
        self.save()

    def withdraw(self, value):
        if value <= self.balance:
            self.transactions.create(
                value=value,
                running_balance=self.balance - value,
                transaction_type='w',  # withdraw
                transaction_status=False
            )

    def __str__(self):
        return f"{self.user.get_full_name()} | {self.shop.title}"


class WalletTransaction(models.Model):
    class TransactionTypeChoices(models.TextChoices):
        deposit = 'd', 'واریز'
        withdraw = 'w', 'برداشت'

    wallet = models.ForeignKey(
        Wallet, on_delete=models.PROTECT, related_name='transactions', verbose_name='کیف پول'
    )
    value = models.BigIntegerField(verbose_name='مبلغ')
    running_balance = models.BigIntegerField(verbose_name='موجودی بعد از تراکنش')
    transaction_type = models.CharField(max_length=2, choices=TransactionTypeChoices.choices, verbose_name='نوع تراکنش')
    transaction_status = models.BooleanField(verbose_name='وضعیت انجام تراکنش')
    description = models.TextField(null=True, blank=True, verbose_name='توضیحات')
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')
    updated = models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')

    class Meta:
        verbose_name_plural = '5. تراکنش های کیف پول'
        verbose_name = 'تراکنش کیف پول'
        ordering = ('-created',)

    def created_jalali(self):
        return f"{jalali_converter(self.created)} ساعت {self.created.hour}:{self.created.minute}"

    created_jalali.short_description = 'تاریخ ایجاد'

    def updated_jalali(self):
        return f"{jalali_converter(self.updated)} ساعت {self.updated.hour}:{self.updated.minute}"

    updated_jalali.short_description = 'تاریخ انجام تراکنش'

    def get_value(self):
        return f"{self.value:,} ت"

    get_value.short_description = 'مبلغ تراکنش'

    def __str__(self):
        return f"{self.wallet}"


class ShopInvoice(models.Model):
    class InvoiceTypeChoices(models.TextChoices):
        pre_invoice = 'pre', 'پیش فاکتور'
        sales_invoice = 'sales', 'فاکتور فروش'

    id = models.CharField(
        max_length=255, default=generate_product_id, primary_key=True, editable=False, unique=True
    )
    shop = models.ForeignKey(
        Shop, on_delete=models.PROTECT, related_name='shop_invoices', verbose_name='فروشگاه'
    )
    user = models.ForeignKey(
        User, on_delete=models.PROTECT, null=True, blank=True, related_name='order_invoices', verbose_name='خریدار'
    )
    address = models.CharField(max_length=255, null=True, blank=True, verbose_name='نشانی')
    date = jmodels.jDateField(null=True, blank=True, verbose_name='تاریخ')
    tax = models.BigIntegerField(default=0, verbose_name='مالیات')
    discount = models.BigIntegerField(default=0, verbose_name='تخفیف')
    transport_cost = models.BigIntegerField(default=0, verbose_name='کرایه باربری')
    invoice_shop = models.CharField(max_length=20, choices=InvoiceTypeChoices.choices, verbose_name='تایپ فاکتور')
    life_time = jmodels.jDateField(null=True, blank=True, verbose_name='تاریخ اعتبار')
    seen = models.BooleanField(default=False, verbose_name='مشاهده شده توسط مشتری')
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')
    updated = models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')

    class Meta:
        verbose_name_plural = '6. فاکتور های فروشگاه'
        verbose_name = 'فاکتور فروشگاه'
        ordering = ('-created',)

shop/forms.py
from django import forms
from jalali_date.widgets import AdminJalaliDateWidget

from shop.models import Contact, ShopInvoice, ShopInvoiceDetail


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('full_name', 'subject', 'phone', 'message', 'shop')


class WalletForm(forms.Form):
    sheba = forms.CharField(
        widget=forms.TextInput
    )


class ShopInvoiceForm(forms.ModelForm):
    class Meta:
        model = ShopInvoice
        fields = '__all__'
        widgets = {
            'date': AdminJalaliDateWidget(
                attrs={'autocomplete': 'off', }
            ),
            'life_time': AdminJalaliDateWidget(
                attrs={'autocomplete': 'off', }
            )
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['shop'].required = False
        self.fields['user'].required = False


class ShopInvoiceDetailForm(forms.ModelForm):
    class Meta:
        model = ShopInvoiceDetail
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'form-control py-5 py-md-3', 'placeholder': 'نام'}
            ),
            'quantity': forms.NumberInput(
                attrs={'class': 'form-control py-5 py-md-3', 'placeholder': 'مقدار'}
            ),
            'quantity_name': forms.TextInput(
                attrs={'class': 'form-control py-5 py-md-3', 'placeholder': 'واحد'}
            ),
            'amount': forms.NumberInput(
                attrs={'class': 'form-control py-5 py-md-3', 'placeholder': 'قیمت'}
            ),
            'count_of_order': forms.TextInput(
                attrs={'class': 'form-control py-5 py-md-3', 'placeholder': 'تعداد'}
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['invoice'].required = False

shop/templates/shop/panel/shop_invoice_list.html
{% extends 'shop/panel/base/_shop_base.html' %}
{% load static %}
{% load humanize %}

{% block title %}
    فاکتور ها | پیکوفلز
{% endblock %}

{% block secondary_title %}
    فاکتور ها
{% endblock %}

{% block secondary_title_detail %}{% endblock %}

{% block content %}

    <div class="row g-6 g-xl-9">
        <div class="card">
            <div class="card-header align-items-center py-5 gap-2 gap-md-5" data-select2-id="select2-data-124-w3ha">
                <!--end::Card title-->
                <!--begin::Card toolbar-->
                <div class="card-toolbar flex-row-fluid justify-content-start gap-5"
                     data-select2-id="select2-data-123-36cp">
                    <a href="{% url 'shop:shop-panel-invoices-create' shop.unique_uuid %}" class="btn btn-primary">افزودن
                        فاکتور</a>
                </div>
                <!--end::Card toolbar-->
            </div>
        </div>

        {% for invoice in page_obj %}
            <div class="col-md-6 col-xl-4">
                <!--begin::Card-->
                <a href="{% url 'shop:shop-panel-invoices-detail' shop.unique_uuid invoice.pk %}"
                   class="card border-hover-primary">
                    <!--begin::Card header-->
                    <div class="card-header border-0 pt-9">
                        <div class="card-toolbar">
                            <span class="badge badge-light-primary fw-bolder me-auto px-4 py-3">
                                شناسه فاکتور: {{ invoice.id }}
                            </span>
                            {% if invoice.invoice_shop == 'pre' %}
                                <span class="badge ms-1 badge-info px-4 py-2">{{ invoice.get_invoice_shop_display }}</span>
                            {% elif invoice.invoice_shop == 'sales' %}
                                <span class="badge ms-1 badge-success px-4 py-2">{{ invoice.get_invoice_shop_display }}</span>
                            {% endif %}
                        </div>
                        <!--end::Card toolbar-->
                    </div>
                    <!--end:: Card header-->
                    <!--begin:: Card body-->
                    <div class="card-body p-9">
                        <!--begin::نام-->
                        <div class="fs-4 fw-bolder text-dark mb-4">
                            خریدار: {{ invoice.user.get_full_name }}
                        </div>
                        <div class="fs-6 fw-bolder text-dark mb-4">
                            {% if invoice.invoice_shop == 'sales' %}
                                تاریخ ثبت:
                                <span dir="rtl">
                                   {{ invoice.date }}
                                </span>
                            {% elif invoice.invoice_shop == 'pre' %}
                                اعتبار فاکتور تا
                                <span dir="rtl">
                                {{ invoice.life_time }}
                                </span>
                            {% endif %}
                        </div>
                        <div class="d-flex flex-wrap mb-5">
                            <!--begin::Due-->
                            <div class="border border-gray-300 border-dashed rounded min-w-125px py-3 px-4 me-7 mb-3">
                                <div class="fs-6 text-gray-800 fw-bolder">
                                    {{ invoice.get_total_invoice_details|intcomma:False }} تومان
                                </div>
                                <div class="fw-bold text-gray-400">جمع خالص فاکتور</div>
                            </div>
                            <!--end::Due-->
                            <!--begin::بودجه-->
                            <div class="border border-gray-300 border-dashed rounded min-w-125px py-3 px-4 mb-3">
                                <div class="fs-6 text-gray-800 fw-bolder">{{ invoice.get_total_invoice_price|intcomma:False }}
                                    تومان
                                </div>
                                <div class="fw-bold text-gray-400">جمع کل فاکتور</div>
                            </div>
                            <!--end::بودجه-->
                        </div>
                    </div>
                    <!--end:: Card body-->
                </a>
                <!--end::Card-->
            </div>
        {% empty %}
            <div class="alert alert-dark">سفارشی برای شما ثبت نشده</div>
        {% endfor %}


    </div>

{% endblock %}

shop/templates/shop/panel/shop_main.html
{% extends 'shop/panel/base/_shop_base.html' %}
{% load static %}

{% block content %}
    <div class="row g-5 g-xl-8">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="text-dark"> {{ request.user.get_full_name }} عزیز به پنل آنلاین مدیریت فروش پیکوفلز خوش
                        آمدید.</h5>
                </div>
            </div>
        </div>
        <div class="col-6 mt-8">
            <a href="{% url 'shop:shop-panel-invoices' shop.unique_uuid %}" class="card bg-primary hoverable card-xl-stretch mb-xl-8">
                <!--begin::Body-->
                <div class="card-body">
                    <!--begin::Svg Icon | path: icons/duotune/ecommerce/ecm008.svg-->
                    <span class="svg-icon svg-icon-gray-100 svg-icon-3x ms-n1">
													<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                                         viewBox="0 0 24 24" fill="none">
														<path opacity="0.3"
                                                              d="M18 21.6C16.3 21.6 15 20.3 15 18.6V2.50001C15 2.20001 14.6 1.99996 14.3 2.19996L13 3.59999L11.7 2.3C11.3 1.9 10.7 1.9 10.3 2.3L9 3.59999L7.70001 2.3C7.30001 1.9 6.69999 1.9 6.29999 2.3L5 3.59999L3.70001 2.3C3.50001 2.1 3 2.20001 3 3.50001V18.6C3 20.3 4.3 21.6 6 21.6H18Z"
                                                              fill="currentColor"></path>
														<path d="M12 12.6H11C10.4 12.6 10 12.2 10 11.6C10 11 10.4 10.6 11 10.6H12C12.6 10.6 13 11 13 11.6C13 12.2 12.6 12.6 12 12.6ZM9 11.6C9 11 8.6 10.6 8 10.6H6C5.4 10.6 5 11 5 11.6C5 12.2 5.4 12.6 6 12.6H8C8.6 12.6 9 12.2 9 11.6ZM9 7.59998C9 6.99998 8.6 6.59998 8 6.59998H6C5.4 6.59998 5 6.99998 5 7.59998C5 8.19998 5.4 8.59998 6 8.59998H8C8.6 8.59998 9 8.19998 9 7.59998ZM13 7.59998C13 6.99998 12.6 6.59998 12 6.59998H11C10.4 6.59998 10 6.99998 10 7.59998C10 8.19998 10.4 8.59998 11 8.59998H12C12.6 8.59998 13 8.19998 13 7.59998ZM13 15.6C13 15 12.6 14.6 12 14.6H10C9.4 14.6 9 15 9 15.6C9 16.2 9.4 16.6 10 16.6H12C12.6 16.6 13 16.2 13 15.6Z"
                                                              fill="currentColor"></path>
														<path d="M15 18.6C15 20.3 16.3 21.6 18 21.6C19.7 21.6 21 20.3 21 18.6V12.5C21 12.2 20.6 12 20.3 12.2L19 13.6L17.7 12.3C17.3 11.9 16.7 11.9 16.3 12.3L15 13.6V18.6Z"
                                                              fill="currentColor"></path>
													</svg>
												</span>
                    <!--end::Svg Icon-->
                    <div class="text-gray-100 fw-bolder fs-2 mb-2 mt-5">{{ shop.shop_invoices.count }}</div>
                    <div class="fw-bold text-gray-100">فاکتور های شما</div>
                </div>
                <!--end::Body-->
            </a>
        </div>
        <div class="col-6 mt-8">
            <a href="#" class="card bg-success hoverable card-xl-stretch mb-xl-8">
                <!--begin::Body-->
                <div class="card-body">
                    <!--begin::Svg Icon | path: icons/duotune/finance/fin006.svg-->
                    <span class="svg-icon svg-icon-white svg-icon-3x ms-n1">
													<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                                         viewBox="0 0 24 24" fill="none">
														<path opacity="0.3"
                                                              d="M20 15H4C2.9 15 2 14.1 2 13V7C2 6.4 2.4 6 3 6H21C21.6 6 22 6.4 22 7V13C22 14.1 21.1 15 20 15ZM13 12H11C10.5 12 10 12.4 10 13V16C10 16.5 10.4 17 11 17H13C13.6 17 14 16.6 14 16V13C14 12.4 13.6 12 13 12Z"
                                                              fill="currentColor"></path>
														<path d="M14 6V5H10V6H8V5C8 3.9 8.9 3 10 3H14C15.1 3 16 3.9 16 5V6H14ZM20 15H14V16C14 16.6 13.5 17 13 17H11C10.5 17 10 16.6 10 16V15H4C3.6 15 3.3 14.9 3 14.7V18C3 19.1 3.9 20 5 20H19C20.1 20 21 19.1 21 18V14.7C20.7 14.9 20.4 15 20 15Z"
                                                              fill="currentColor"></path>
													</svg>
												</span>
                    <!--end::Svg Icon-->
                    <div class="text-white fw-bolder fs-2 mb-2 mt-5">+{{ shop.score }}</div>
                    <div class="fw-bold text-white">امتیاز شما</div>
                </div>
                <!--end::Body-->
            </a>
        </div>
        <div class="col-12">
            <!--begin::نمودار ها Widget 3-->
            <div class="card card-xl-stretch mb-xl-8">
                <!--begin::Header-->
                <div class="card-header border-0 pt-5">
                    <h3 class="card-title align-items-start flex-column">
                        <span class="card-label fw-bolder fs-3 mb-2">نمودار فروش یک هفته گذشته</span>
                    </h3>
                </div>
                <!--end::Header-->
                <!--begin::Body-->
                <div class="card-body">
                    <canvas id="weeklyInvoice" aria-label="chart" class="h-auto h-md-500px"></canvas>
                </div>
                <!--end::Body-->
            </div>
            <!--end::نمودار ها Widget 3-->
        </div>
    </div>
{% endblock %}

{% block meta_js_code %}
    <script src="{% static 'site_statics/js/chart.min.js' %}"></script>
    <script>
        console.log({{ weekly_records|safe }})
        let chrt = document.getElementById("weeklyInvoice").getContext("2d");
        new Chart(chrt, {
            type: 'bar',
            data: {
                labels: {{ weekly_records|safe }}[0],
                datasets: [{
                    label: '# جمع کل فاکتور',
                    data: {{ weekly_records|safe }}[1],
                    borderWidth: 1,
                    borderColor: '#FF6384',
                    backgroundColor: '#FF6384',
                    pointStyle: 'circle',
                    pointRadius: 10,
                    pointHoverRadius: 15
                }]
            },
            options: {
                scales: {
                    x: {
                        ticks: {
                            font: {
                                size: 12,
                            }
                        }
                    }
                },
                responsive: true,
                maintainAspectRatio: false,
                aspectRatio: 1
            },
        });
    </script>
{% endblock %}