blog/urls.py
from django.urls import path
from .views import (
    ArticleListView,
    ArticleDetailView
)

app_name = 'blog'
urlpatterns = [
    path('', ArticleListView.as_view(), name='blog-list'),
    path('<int:pk>/<title>', ArticleDetailView.as_view(), name='blog-detail'),
]

core/urls.py
from django.urls import path

from metallurgy.views import (
    WorkSampleListView,
    WorkSampleDetailView,
    WorkSampleCategoryListView,
    CategoriesListView
)
from .views import (
    Home,
    AboutUsView,
    CreateContactView,
    PlatformMvpView,
    IronCalculatorTemplateView
)

app_name = 'core'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('about-us/', AboutUsView.as_view(), name='about-us'),
    path('contact-us/', CreateContactView.as_view(), name='contact-us'),
    # path('faq/', QuestionListView.as_view(), name='faq'),
    path('calculator/', IronCalculatorTemplateView.as_view(), name='calculator'),
    path('vehicles/', PlatformMvpView.as_view(), name='platform-mvp'),

    path('portfolios/', WorkSampleListView.as_view(), name='work-sample-list'),
    path('portfolios/categories/', CategoriesListView.as_view(), name='work-sample-categories'),
    path(r'portfolios/category-<slug>/<int:pk>', WorkSampleCategoryListView.as_view(),
         name='work-sample-category-list'),
    path('portfolios/<int:pk>/<str:title>', WorkSampleDetailView.as_view(), name='work-sample-detail'),
]

picofelez/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from blog.sitemap import ArticleSitemap
from core.sitemap import StaticViewSitemap
from metallurgy.sitemap import WorkSampleSitemap
from product.sitemap import ProductSitemap, CategorySitemap

sitemaps = {
    "statics": StaticViewSitemap,
    "products": ProductSitemap,
    "portfolio": WorkSampleSitemap,
    "articles": ArticleSitemap,
    "categories": CategorySitemap
}

urlpatterns = [
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap"
    ),

    path('', include('core.urls')),
    path('products/', include('product.urls')),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls')),
    path('metallurgy/', include('metallurgy.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from .views import (
    ProductDetailView,
    ProductListView,
    MultipleProductDetailView
)

app_name = 'product'
urlpatterns = [
    path('', ProductListView.as_view(), name='product-list'),
    path('vehicles/<pk>', ProductDetailView.as_view(), name='product-detail'),
    path('<pk>/<title>', MultipleProductDetailView.as_view(), name='multiple-product-detail')
]

shop/urls.py
from django.urls import path
from .views import (
    ShopDetailView,
    create_shop_contact,
    ShopProductsView,
    ShopRatingView,

    ShopListView,
    register_shop,
    register_shop_seller_information_create,
    register_shop_create,

    # panel
    ShopAccountMainView,
    ShopProductsListView,
    ShopProductUpdateView,
    ShopProductCreateView,
    ShopOrderListView,
    ShopOrderDetailView,
    ShopOrderUpdateView,
    ShopUpdateView,
    shop_wallet_view,
    ShopUpdateProductPriceView,
    ShopInvoiceListListView,
    ShopInvoiceDetailDetailView,
    create_shop_invoice_view,
    update_shop_invoice_view,
    customer_for_invoice_ajax_view
)

app_name = 'shop'
urlpatterns = [
    path('shops/register-shop/', register_shop, name='register-shop'),
    path('shops/', ShopListView.as_view(), name='shop-list'),
    path('<slug>', ShopDetailView.as_view(), name='shop-detail'),
    path('<slug>/contact', create_shop_contact, name='shop-contact'),
    path('<slug>/products', ShopProductsView.as_view(), name='shop-products'),
    path('<slug>/rating', ShopRatingView.as_view(), name='shop-rating'),

    # ajax urls
    path(
        'shops/register-shop/seller-information-create',
        register_shop_seller_information_create,
        name='seller-information-create'
    ),
    path(
        'shops/register-shop/data-create',
        register_shop_create,
        name='shop-data-create'
    ),

    # panel
    path('shop/panel/<unique_uuid>', ShopAccountMainView.as_view(), name='shop-panel-main'),
    path('shop/panel/<unique_uuid>/update', ShopUpdateView.as_view(), name='shop-panel-update'),
    # path('shop/panel/<unique_uuid>/wallet', shop_wallet_view, name='shop-panel-wallet'),

    # path(
    #     'shop/panel/<unique_uuid>/products',
    #     ShopProductsListView.as_view(),
    #     name='shop-panel-products'
    # ),
    # path(
    #     'shop/panel/<unique_uuid>/products/update/<str:pk>',
    #     ShopProductUpdateView.as_view(),
    #     name='shop-panel-products-update'
    # ),
    # path(
    #     'shop/panel/<unique_uuid>/products/update/price/<str:pk>',
    #     ShopUpdateProductPriceView.as_view(),
    #     name='shop-panel-products-update-price'
    # ),
    # path(
    #     'shop/panel/<unique_uuid>/products/create',
    #     ShopProductCreateView.as_view(),
    #     name='shop-panel-products-create'
    # ),

    # path(
    #     'shop/panel/<unique_uuid>/orders',
    #     ShopOrderListView.as_view(),
    #     name='shop-panel-orders'
    # ),
    # path(
    #     'shop/panel/<unique_uuid>/orders/<int:pk>',
    #     ShopOrderDetailView.as_view(),
    #     name='shop-panel-orders-detail'
    # ),
    # path(
    #     'shop/panel/<unique_uuid>/orders/update/<int:pk>',
    #     ShopOrderUpdateView.as_view(),
    #     name='shop-panel-orders-update'
    # ),

    # special shops
    path(
        'shop/panel/<unique_uuid>/invoices',
        ShopInvoiceListListView.as_view(),
        name='shop-panel-invoices'
    ),
    path(
        'shop/panel/<unique_uuid>/invoices/create',
        create_shop_invoice_view,
        name='shop-panel-invoices-create'
    ),
    path(
        'shop/panel/<unique_uuid>/invoices/create/customer',
        customer_for_invoice_ajax_view,
        name='shop-panel-invoices-create-customer'
    ),
    path(
        'shop/panel/<unique_uuid>/invoices/update/<str:pk>',
        update_shop_invoice_view,
        name='shop-panel-invoices-update'
    ),
    path(
        'shop/panel/<unique_uuid>/invoices/<str:pk>',
        ShopInvoiceDetailDetailView.as_view(),
        name='shop-panel-invoices-detail'
    ),
]

product/models.py
import random

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.html import format_html
from django.utils.text import slugify

from extensions.utils import upload_product_image_path, generate_product_id, jalali_converter
from product.managers import PublishedProductsManager
from shop.models import Shop

# Create your models here.
User = get_user_model()


class Category(models.Model):
    """
    The category main model.
    """
    parent = models.ForeignKey(
        "self", on_delete=models.CASCADE, null=True, blank=True, related_name='sub_cats', verbose_name='دسته بندی والد'
    )
    name = models.CharField(max_length=100, verbose_name='نام دسته')
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')
    description = RichTextField(null=True, blank=True, verbose_name='توضیحات')
    slug = models.SlugField(
        max_length=255, null=True, blank=True, verbose_name="اسلاگ"
    )
    meta_keywords = models.CharField(max_length=255, null=True, blank=True, verbose_name='کلمات کلیدی')
    meta_description = models.CharField(max_length=255, null=True, blank=True, verbose_name='توضیحات')
    meta_title = models.CharField(max_length=255, null=True, blank=True, verbose_name='عنوان متا')
    pinned = models.BooleanField(default=False, verbose_name="پین شده")
    image = models.ImageField(upload_to=upload_product_image_path, null=True, blank=True, verbose_name='تصویر')
    image_url = models.URLField(null=True, blank=True, verbose_name='آدرس تصویر')
    summary = RichTextUploadingField(null=True, blank=True, verbose_name='توضیحات')
    icon = models.CharField(max_length=50, null=True, blank=True, verbose_name='آیکون')


    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = '2. دسته بندی ها'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("core:work-sample-category-list", args=[self.slug, self.pk])

    def __str__(self):
        return self.name


class Product(models.Model):
    """
    The product main model,
    Many-To-One relationship with Shop,
    Many-to-One relationship with User,
    Many-To-Many relationship wit Category.
    """

    class ProductTypeChoices(models.TextChoices):
        multiple_seller = 'multiple', 'چند فروشنده'
        solo_seller = 'solo', 'تک فروشنده'

    id = models.CharField(
        max_length=255, default=generate_product_id, primary_key=True, editable=False, unique=True
    )
    shop = models.ForeignKey(
        Shop, on_delete=models.PROTECT, null=True, blank=True, related_name='shop_products', verbose_name='فروشگاه'
    )
    maker = models.ForeignKey(
        User, on_delete=models.PROTECT, null=True, blank=True, related_name='user_products', verbose_name='سازنده'
    )
    title = models.CharField(max_length=100, verbose_name='عنوان')
    description = RichTextUploadingField(null=True, blank=True, verbose_name='توضیحات')
    summary = models.CharField(max_length=255, null=True, blank=True, verbose_name='خلاصه')
    keywords = models.CharField(max_length=255, null=True, blank=True, verbose_name='کلمات کلیدی')
    price = models.BigIntegerField(verbose_name='قیمت', null=True, blank=True, )
    stock = models.IntegerField(verbose_name='موجودی در انبار', null=True, blank=True, )
    quantity = models.CharField(max_length=50, verbose_name='واحد', null=True, blank=True)
    weight = models.CharField(max_length=100, verbose_name='وزن', null=True, blank=True)
    length = models.CharField(max_length=100, verbose_name='طول', null=True, blank=True)
    width = models.CharField(max_length=100, verbose_name='ضخامت', null=True, blank=True)
    image = models.ImageField(upload_to=upload_product_image_path, null=True, blank=True, verbose_name='تصویر محصول')
    image_url = models.URLField(null=True, blank=True, verbose_name='آدرس تصویر')
    is_active = models.BooleanField(default=True, verbose_name='فعال/غیرفعال')
    is_confirmed = models.BooleanField(default=True, verbose_name='تائید شده/نشده')
    categories = models.ManyToManyField(
        Category, related_name='products', verbose_name='دسته بندی ها'
    )
    purchase_limit = models.IntegerField(null=True, blank=True, verbose_name='محدودیت خرید')
    product_type = models.CharField(
        max_length=20, choices=ProductTypeChoices.choices, default=ProductTypeChoices.solo_seller, verbose_name='نوع'
    )
    shops = models.ManyToManyField(
        Shop, related_name='multiple_products', blank=True, verbose_name='فروشنده ها'
    )
    created = models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')
    updated = models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = '1. محصولات'
        ordering = ('-created',)

    objects = models.Manager()
    published = PublishedProductsManager()

    def get_thumbnail(self):
        return format_html(f"<img width=100 height=75 style='border-radius: 5px;' src='{self.image.url}'>")

    get_thumbnail.short_description = "تصویر محصول"

    def get_price(self):
        if self.price:
            return f"{self.price:,}"
        return 0

    get_price.short_description = 'قیمت'

    def get_absolute_url(self):
        if self.product_type == 'solo':
            return reverse('product:product-detail', args=[self.id, self.get_replaced_title()])
        elif self.product_type == 'multiple':
            return reverse('product:multiple-product-detail', args=[self.id, self.get_replaced_title()])

    def get_replaced_title(self):
        return self.title.replace(' ', '-')

    def __str__(self):
        return f"{self.title} - {self.shop if self.shop else f'{self.shops.count()} فروشنده'}"


class FavoriteProduct(models.Model):
    """
    The FavoriteProduct main model,
    Many-To-One relationship with User,
    Many-To-One relationship with product.
    """
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='favorites', verbose_name='کاربر'
    )
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='user_favorites', verbose_name='محصول'
    )
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')

    class Meta:
        verbose_name = 'محصول مورد علاقه'
        verbose_name_plural = '3. محصولات مورد علاقه'
        ordering = ('-created',)

    def __str__(self):
        return f"{self.user.get_full_name()} | {self.product.title}"


class PriceHistory(models.Model):
    """
    The Product Price History main model.
    """
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='price_histories', verbose_name='محصول')
    price = models.BigIntegerField(verbose_name='قیمت')
    is_confirmed = models.BooleanField(verbose_name='تائید شده/نشده')
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')

    class Meta:
        verbose_name = 'تغیر قیمت'
        verbose_name_plural = '4. تغییرات قیمت'

    def created_jalali(self):
        return jalali_converter(self.created)

    def __str__(self):
        return f"{self.product.title} - {self.price:,}"

product/views.py
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import DetailView
from django.views.generic.edit import FormMixin
from django_filters.views import FilterView

from core.forms import RatingForm
from core.models import Rating
from .filters import ProductFilter
from .models import Product


# Create your views here.


class ProductDetailView(FormMixin, DetailView):
    """
    This view show a product detail.
    """
    queryset = Product.published.all()
    template_name = 'product/product_detail.html'
    context_object_name = 'product'
    form_class = RatingForm
    success_message = 'نظر شما با موفقیت ارسال شد.'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        form = self.get_form()
        form.fields['comment'].required = True
        form.fields['rating'].required = True

        if form.is_valid() and self.request.user.is_authenticated:
            rate = Rating(
                comment=form.cleaned_data.get('comment'),
                stars=form.cleaned_data.get('rating'),
                content_object=self.get_object(),
                user=self.request.user
            )
            rate.save()

            messages.success(request, 'نظر شما با موفقیت ارسال شد.')
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
        context['price_data'] = [price.price for price in self.get_object().price_histories.all()]
        context['price_labels'] = [price.created_jalali() for price in self.get_object().price_histories.all()]
        return context

    def get_success_url(self):
        return reverse_lazy('product:product-detail', args=[self.get_object().id])


class ProductListView(FilterView):
    """
    This view show all published products.
    """
    queryset = Product.objects.filter(product_type='multiple', is_active=True)
    template_name = 'product/product_list.html'
    paginate_by = 15
    filterset_class = ProductFilter


class MultipleProductDetailView(DetailView):
    queryset = Product.objects.filter(is_active=True)
    template_name = 'product/multiple_product_detail.html'

product/templates/product/multiple_product_detail.html
{% extends 'core/base/_base.html' %}
{% load static %}
{% load humanize %}
{% load widget_tweaks %}

{% block title %}{{ object.title }} | پیکوفلز{% endblock %}

{% block meta_tags %}
    <meta property="og:url"
          content="https://picofelez.ir/products/{{ object.pk }}/{{ object.get_replaced_title }}">
    <meta property="og:type" content="website">
    <meta property="og:title" content="پیکوفلز | {{ object.title }}">
    <meta property="og:description" content="{{ object.summary }}">

    <!-- Twitter Meta Tags -->
    <meta property="twitter:domain" content="picofelez.ir">
    <meta property="twitter:url"
          content="https://picofelez.ir/products/{{ object.pk }}/{{ object.get_replaced_title }}">
    <meta name="twitter:title" content="پیکوفلز | {{ object.title }}">
    <meta name="twitter:description" content="{{ object.summary }}">

    <meta name="keywords" content="{{ object.keywords }}">

    <meta name="title" content="پیکوفلز | {{ object.title }}">
    <meta name="description" content="{{ object.summary }}">
{% endblock %}

{% block analytics_script %}{% endblock %}
{% block header_content %}
    {% include 'core/base/_plat_mvp_header.html' %}
{% endblock %}

{% block footer_content %}
{% endblock %}

{% block content %}
    <section class="inner-page" id="product-page">
        <!-- breadcrumb start -->
        <section class="page-title-box container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="container">
                        <div class="row">
                            <div class="col-12 px-0">
                                <h3 class="font-vazir-bold-fd">پیکو ابزار</h3>
                                <p>مرجع تخصصی ابزار</p>
                                <nav aria-label="breadcrumb">
                                    <ol class="breadcrumb">
                                        <li class="breadcrumb-item">
                                            <a href="{% url 'core:home' %}">خانه</a>
                                        </li>
                                        <li class="breadcrumb-item">
                                            <a href="{% url 'product:product-list' %}">محصولات</a>
                                        </li>
                                        <li class="breadcrumb-item active" aria-current="page">
                                            {{ product.title }}
                                        </li>
                                    </ol>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- breadcrumb end -->
        <section class="container">
            <div class="row">
                <div class="col-12">
                    <div class="page-content">
                        <div class="row">
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="col-12 mb-2">
                                        <div class="alert alert-success">
                                            {{ message }}
                                        </div>
                                    </div>
                                {% endfor %}

                            {% endif %}

                            <div class="col-12 col-lg-4 mb-3">
                                <h1 class="h5 title font-vazir-bold-fd mb-4">
                                    {{ product.title }}
                                </h1>
                                <div class="rounded-card box-shadow">
                                    <div class="text-center">
                                        <img
                                                src="

                                                        {% if product.image %}{{ product.image.url }}{% else %}{{ product.image_url }}{% endif %}"
                                                alt="{{ product.title }}"
                                                class="multiple-product-detail-img"
                                        />
                                        <hr>
                                        <div>
                                            {% if product.width %}
                                                <span class="badge border rounded text-black">
                                                   ضخامت {{ product.width }}
                                                </span>
                                            {% endif %}
                                            {% if product.weight %}
                                                <span class="badge border rounded text-black">
                                                   وزن تقریبی {{ product.weight }}
                                                </span>
                                            {% endif %}
                                            {% if product.length %}
                                                <span class="badge border rounded text-black">
                                                   طول {{ product.length }}
                                                </span>
                                            {% endif %}
                                        </div>
                                        <a href="tel:09199060659" class="btn btn-purple mt-3">
                                            <i class="fas fa-phone"></i>
                                            برای خرید تماس بگیرید
                                        </a>
                                    </div>
                                </div>
                                <div class="rounded-card box-shadow my-3">
                                    <a href="{% url 'core:calculator' %}" class="btn btn-outline-purple w-100">محاسبه
                                        وزن {{ object.title }}</a>
                                </div>
                            </div>

                            {% if product.shops.all %}
                                <div class="col-12 col-md-8 mb-3 mt-4 mt-md-0">
                                    <div class="row">
                                        <div class="col-12 mb-3">
                                            <p class="h5 title font-vazir-bold-fd">فروشنده ها</p>
                                        </div>


                                        {% for shop in product.shops.all %}
                                            <div class="col-12 mb-4">
                                                <div class="rounded-card box-shadow">
                                                    <div class="d-flex justify-content-between align-items-center">
                                                        <p class="font-vazir-bold-fd w-50">
                                                            {{ shop.title }}
                                                        </p>
                                                        <p class="w-25">
                                                            <span class="font-vazir-bold-fd">امتیاز: </span>
                                                            {{ shop.score }}
                                                        </p>
                                                        <p class="w-25 text-end">
                                                            <span class="font-vazir-bold-fd">شهر: </span>
                                                            {{ shop.location }}
                                                        </p>
                                                    </div>
                                                    <div>
                                                        <a href="{% url 'shop:shop-detail' shop.slug %}"
                                                           class="btn btn-outline-success btn-sm">
                                                            <i class="fas fa-shop"></i>
                                                            درباره فروشنده
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endfor %}


                                    </div>
                                </div>
                            {% endif %}

                            {% if product.description %}
                                <div class="col-12 col-md-8 mb-3 mt-4 mt-md-0">
                                    <div class="row">
                                        <div class="col-12 mb-3">
                                            <p class="h5 title font-vazir-bold-fd">درباره محصول</p>
                                        </div>
                                        <div class="col-12 mb-4">
                                            {{ product.description|safe }}
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}